# -*- coding: utf-8 -*-
"""10869

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16yINcirk98EfNoQbD9BB68SwgXmaWd6k
"""

A,B=map(int,input().split()) #정수 2개를 입력 받아 연산결과를 출력
print(A+B)
print(A-B)
print(A*B)
print(int(A/B))
print(A%B)